const i18n = {
  en: {
    ENVIRONMENT: {
      STAGING: 'test',
      PRODUCTION: 'production',
      DEVELOPMENT: 'development',
    },
    ROOT: {
      TITLE: 'Create Next App',
      DESCRIPTION: 'Generated by create next app',
    },
  },
};

export default i18n;
